#!/bin/sh

# TODO I DON"T get this

if [ "$DEPLOYMENT_GROUP_NAME" == "GoWatcherStaging" ]
then
    sed -i -e 's/%%%SYSTEM%%%/GoWatcherStaging/g' /opt/laura/watcher/setup_environment.sh
elif [ "$DEPLOYMENT_GROUP_NAME" == "GoWatcherProduction" ]
then
    sed -i -e 's/%%%SYSTEM%%%/GoWatcherProduction/g' /opt/laura/watcher/setup_environment.sh

chmod +x /opt/laura/watcher/setup_environment.sh
